fix: add cover_image attachment to Blog model
- Add  to Blog model
- Update _blog_grid.html.erb to use  instead of non-existent  method
- Fixes NoMethodError: undefined method 'cover_image_url' on news page